//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string IP_Address { get; set; }
        public string Name { get; set; }
        public int Port_NO { get; set; }
        public int No_Of_Job_Completed { get; set; }
        public string Currently_Doing_Any_Job { get; set; }
        public string Name_Of_Last_Completed_Job { get; set; }
        public string Result_Of_Last_Completed_Job { get; set; }
        public string Connected { get; set; }
    }
}
